source 'https://rubygems.org'
ruby '2.1.2'
gem 'sinatra'
gem "activerecord"
gem "sinatra-activerecord"
gem 'mysql2', '0.3.17'
gem 'rake'
gem 'sinatra-flash'
gem 'rerun'  # Auto load server
gem 'faker' # fake data for seed
gem 'thin' # server
gem 'populator'
gem 'pry' # debug
gem 'sinatra-contrib',require: false
gem 'sinatra-flash' # flash